In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
grades = [70, 48 ,76, 56, 39, 62 ,53]
grades

[70, 48, 76, 56, 39, 62, 53]

In [3]:
def exchange(a):
    return(int(np.sqrt(a)*10))

In [4]:
print(exchange(75))

86


In [5]:
list(map(exchange, grades))

[83, 69, 87, 74, 62, 78, 72]

## 第一題

In [6]:
import random

In [7]:
#最準星座分析

a = ['牡羊座', '金牛座', '雙子座', '巨蟹座', '獅子座', '處女座', '天秤座', '天蠍座', '射手座', '摩羯座', '水瓶座', '雙魚座']
b = ['今天','明天','下周','在未來一個月','今年','過往人生中','本周','在上半年度','在下半年度','到年底之前','近期','每個假日']
c = ['睡覺的時候都會閉上眼睛',
     '可能會發生好事,可能沒有',
     '肚子餓的時候會吃點東西,不然會很餓',
     '洗澡時從來不穿衣服',
     '熬夜時都會比較晚睡',
     '煮泡麵的時候可能會需要加熱水',
     '打報告的時候都會記得存檔',
     '準備團體報告時,都不喜歡雷隊友',
     '每過60秒,人生就會少掉一分鐘',
     '都會吐出二氧化碳',
     '外出的時候都會鎖門',
     '煮完東西都有關瓦斯的必要',
     '吃橘子的時候習慣剝皮再吃']

C = random.choice(a)
time = random.choice(b)
things = random.choice(c)

print( "{}的朋友{}{}".format(C, time, things) )

摩羯座的朋友下周都會吐出二氧化碳


## 第二題

In [8]:
from ipywidgets import interact

In [9]:
def move(n = 1):
    print(" "*n + "OuO")
interact(move, n = (1,40))    

interactive(children=(IntSlider(value=1, description='n', max=40, min=1), Output()), _dom_classes=('widget-int…

<function __main__.move(n=1)>

In [10]:
def move(n = 1):
    print( " "*n + "@_@" + " "*(40-n)+" "*(40-n) + "OuO")
interact(move, n = (1,40))  

interactive(children=(IntSlider(value=1, description='n', max=40, min=1), Output()), _dom_classes=('widget-int…

<function __main__.move(n=1)>

In [11]:
def move(n = 1):
    print(" "*n + "OuO" + " "*n)
interact(move, n = (1,40))  

interactive(children=(IntSlider(value=1, description='n', max=40, min=1), Output()), _dom_classes=('widget-int…

<function __main__.move(n=1)>

## 第三題

In [12]:
def tree(x):
    for i in range(x):
        print(" "*(x-i) + "*"*i + "1" + "*"*i + " "*(x-i)  )

tree(15)

               1               
              *1*              
             **1**             
            ***1***            
           ****1****           
          *****1*****          
         ******1******         
        *******1*******        
       ********1********       
      *********1*********      
     **********1**********     
    ***********1***********    
   ************1************   
  *************1*************  
 **************1************** 


In [13]:
def diamond(x):
    print(" "*(x+1) + "*")
    for i in range(x):
        print(" "*(x-i) + "*" + " "*(2*i+1) + "*" + " "*(x-i)  )
    print("*" + " "*(2*x+1) + "*")
    for i in range(x):
        print(" "*(i+1) + "*" + " "*(2*(x-i)-1) + "*" )
    print(" "*(x+1) + "*")

diamond(3)

    *
   * *   
  *   *  
 *     * 
*       *
 *     *
  *   *
   * *
    *


## 第四題

In [38]:
grades = np.random.randint(100, size = [3,10,5]) #三個班 每班10人 每人5科
print(grades)

[[[18 92 22 15 95]
  [41 59 17 74 45]
  [45 71 78 43  7]
  [47 58 46 52 34]
  [86 98 33 27 48]
  [17 69 12 13 55]
  [52 27 42 33 43]
  [34 94 32 18 30]
  [99 53 16 44 89]
  [29 21 86 73  1]]

 [[13 32 66  9 17]
  [57 59 72 97  2]
  [33 15 71 29 13]
  [53 87 81 83 95]
  [97  1 26 44 42]
  [24 81 73 13 69]
  [48 91 71 66 68]
  [95 26 19 14 34]
  [27 33 39  4 63]
  [11 10 71 86 17]]

 [[ 1 18 70 68 13]
  [13 43 46 17 39]
  [91 81 98  3 60]
  [21 68 92 65 32]
  [59 41 87 60 14]
  [ 7 51 25 83 49]
  [28 68 17 31 99]
  [ 6 41 11 13 81]
  [22 45 66 38 86]
  [40 78 97 92 15]]]


In [36]:
weights = np.array([0.25, 0.25, 0.25, 0.15, 0.10])

In [40]:
result = np.dot(grades,weights)

In [41]:
print(result)

[[44.75 44.85 55.65 48.95 63.1  31.95 39.5  45.7  57.5  45.05]
 [30.8  61.75 35.4  77.2  41.8  53.35 69.2  40.5  31.65 37.6 ]
 [33.75 31.95 73.95 58.2  57.15 38.1  42.8  24.55 47.55 69.05]]
